### ISSUE TITLE
SonarQube 9.9.x failures

### ISSUE THREAD

**Issue by Goldcap** [kogitant/sonar-slack-notifier-plugin#40]
Just as an FYI, after the recent upgrade to 9.9.x I'm getting the following error. My config looks identical but happy to admit I haven't played with it too much:

```
2023.06.20 14:59:59 ERROR ce[AYjaZHTqClT-Y9Te02gs][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.komodin.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask failed
java.lang.NullPointerException: Cannot invoke "com.komodin.sonar.slacknotifier.sonarclient.MeasureHistory.getMeasures()" because "response" is null
	at com.komodin.sonar.slacknotifier.sonarclient.SonarClient.getMeasures(SonarClient.java:63)
	at com.komodin.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask.finished(SlackPostProjectAnalysisTask.java:97)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:102)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:93)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:89)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:61)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

I'm using the new fork here:

https://github.com/komodin/sonar-slack-notifier-plugin

Thanks for taking a look if you have a minute.

**Comment by singhragvendra503** [comment]
You can try with updated plugin https://github.com/komodin/sonar-slack-notifier-plugin and they @MartoEporedia @OllowainT  are made this plugin

**Comment by revealbd** [comment]
Also faced this issue, in our case it was expired "Server Token" in plugin configuration.

**Comment by Bohdandn** [comment]
Also faced this issue, in our case it was expired "Server Token" in plugin configuration.
